name: JupyterLab
channels:
  - pytorch
  - nvidia
  - numba
  - conda-forge
dependencies:
  - python
  - ffmpeg
  - jupyter_server
  - jupyterlab
  - matplotlib
  - micromamba
  - numba
  - numpy
  - nvitop
  - pandas
  - pip
  - pip:
    - jupyterlab-quarto
  - pytorch
  - pytorch-cuda=12.1
  - scikit-learn
  - scipy
  - sympy
  - torchaudio
  - torchvision
